;; Exercise 1.9: Each of the following two procedures defines a method
;; for adding two positive integers in terms of the procedures inc,
;; which increments its argument by 1, and dec, which decrements its
;; argument by 1.

(define (+ a b)
  (if (= a 0) b
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0) b
      (+ (dec a) (inc b))))

;; Using the substitution model, illustrate the process generated by
;; each procedure in evaluating (+ 4 5). Are these processes iterative
;; or recursive?

;; Solution
;; Process generated by the first procedure
;; (+ 4 5)
;; (inc (+ 3 5))
;; (inc (inc (+ 2 5)))
;; (inc (inc (inc (+ 1 5))))
;; (inc (inc (inc (inc (+ 0 5)))))
;; (inc (inc (inc (inc 5))))
;; (inc (inc (inc 6)))
;; (inc (inc 7))
;; (inc 8)
;; 9
;;
;; Since the process builds up a chain of deferred operations before
;; performing them when the value of the parameter a reaches zero,
;; this is a recursive process. Also note that the shape of the
;; process increases before decreasing.

;; Process generated by the second procedure
;; (+ 4 5)
;; (+ 3 6)
;; (+ 2 7)
;; (+ 1 8)
;; (+ 0 9)
;; 9
;;
;; The state of this process at any step can be summarized by the
;; variables a and b. There also exists a rule that describes how a
;; and b should be updated from state to state and when process should
;; terminate. These existence of these characterists make it an
;; iterative process. Note also that this process does not have
;; deferred operations and that the shape of the process remains
;; constant till the last step.
